src/pages/pools/components/AddLiquidity/index.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-336
=> HYP-336: Select same token and chain issue within add liquidity.

src/components/CustomTooltip.tsx, src/context/Transaction.tsx, src/pages/bridge/components/TransactionFee.tsx
https://biconomy-tech.atlassian.net/browse/HYP-318
=> HYP-318: Show single row showing the net transaction fee (further breakdown in tooltip)

src/components/CustomTooltip.tsx, src/context/TransactionInfoModal.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/TransactionFee.tsx, src/pages/bridge/components/TransferInfoModal.tsx, src/pages/bridge/components/TransferModal/index.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-344
=> HYP-344: V2 : Bridge : Transfer Modal : Error Handling when user switches the networks in transition.

src/pages/bridge/Bridge.tsx, src/pages/bridge/components/TransactionFee.tsx
https://biconomy-tech.atlassian.net/browse/HYP-318
=> HYP-318: Bridge : Show single row showing the net transaction fee (further breakdown in tooltip)

src/pages/bridge/Bridge.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/TransactionFee.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-348
=> HYP-348-staging: V2 : Bridge : Min value is 0 for Ethereum.

src/context/Transaction.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/TransactionFee.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-349
=> HYP-349-staging: V2 : Bridge : Remove Rewards & Token gas price code logic from console

src/pages/bridge/components/AmountInput.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-348
=> HYP-348: V2 : Bridge : Min value is 0 for Ethereum. (integration-v2)

src/components/CustomTooltip.tsx, src/context/Transaction.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/TransactionFee.tsx
https://biconomy-tech.atlassian.net/browse/HYP-318
=> HYP-318: Bridge : Show single row showing the net transaction fee (further breakdown in tooltip) (master-v2)

src/components/CustomTooltip.tsx, src/context/Transaction.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/TransactionFee.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-348
=> HYP-348: Bridge : Min value is 0 for Ethereum. (master-v2)

src/components/CustomTooltip.tsx, src/context/Transaction.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/TransactionFee.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HYP-349
=> HYP-349: V2 : Bridge : Please remove Rewards & Token gas price code logic from console (master-v2)

src/pages/farms/components/AddStakingPosition/index.tsx, src/pages/farms/components/ManageStakingPosition/index.tsx, src/pages/pools/components/AddLiquidity/index.tsx, src/pages/pools/components/IncreaseLiquidity/index.tsx, src/pages/pools/components/ManageLiquidity/index.tsx
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HP-101
=> HP-101: Hyphen UI: Rejecting a metamask tx causes an error on the UI (pools & farms).

src/components/Footer.tsx, src/components/Toggle.tsx, src/context/Hyphen.tsx, src/context/Notifications.tsx, src/context/TokenApproval.tsx, src/hooks/useErrorModal.ts, src/hooks/useLoading.ts, src/hooks/useModal.ts, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/ErrorModal.tsx, src/pages/bridge/components/TransactionDetailModal/index.tsx, src/pages/bridge/components/TransferModal/index.tsx, src/pages/bridge/components/UserInfoModal/index.tsx, src/pages/farms/FarmsInfo.tsx, src/pages/pools/components/IncreaseLiquidity/index.tsx, src/utils/toFixed.ts
**Fixes:**
https://biconomy-tech.atlassian.net/browse/HP-38
Removes unused imports, variables & lint warnings.
=> feat: removed linting warnings. (to master-v2)

.husky/pre-commit, lint-staged.js, package.json, src/App.test.tsx, src/setupTests.ts, yarn.lock
https://biconomy-tech.atlassian.net/browse/HP-33
https://biconomy-tech.atlassian.net/browse/HP-40
=> HP-33 / HP-40: Hyphen UI: Pre-commit hooks for code formatting, linting and testing. (to integration-v2)

.husky/pre-commit, lint-staged.js, package.json, src/App.test.tsx, src/setupTests.ts, yarn.lock
https://biconomy-tech.atlassian.net/browse/HP-33
https://biconomy-tech.atlassian.net/browse/HP-40
=> HP-33 / HP-40: Hyphen UI: Pre-commit hooks for code formatting, linting and testing. (to master-v2)

src/components/Select.tsx, src/hooks/useTokens.ts, src/pages/bridge/components/TokenSelector.tsx
**Changes:**
Uses token color from tokens API.
=> HYP-227 to staging-v2

src/components/Select.tsx, src/hooks/useTokens.ts, src/pages/bridge/components/TokenSelector.tsx
Uses token color from tokens API.
—
=> HYP-227 to integration-v2

src/pages/farms/components/AddStakingPosition/index.tsx
=> HYP-174: fixes reward token symbol for add stakign position.

src/assets/images/no-select-icon.svg, src/components/Select.tsx, src/pages/bridge/components/AmountInput.tsx, src/pages/bridge/components/CallToAction.tsx, src/pages/bridge/components/TokenSelector.tsx
=> HYP-174: UI changes.

package.json, src/App.tsx, src/components/Buttons/SecondaryButtonLight.tsx, src/components/ErrorFallback.tsx, src/components/MailTo.tsx, src/index.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/UserInfoModal/index.tsx, yarn.lock
https://biconomy-tech.atlassian.net/browse/HP-130
**Depends on:**
#181
=> HP-130: Lazy loading components which are not required immediately. (to staging-v2).

package.json, src/App.tsx, src/components/Buttons/SecondaryButtonLight.tsx, src/components/ErrorFallback.tsx, src/components/MailTo.tsx, src/index.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/UserInfoModal/index.tsx, yarn.lock
https://biconomy-tech.atlassian.net/browse/HP-130
**Depends on:**
#181
—
=> HP-130: Lazy loading components which are not required immediately. (to integration-v2).

src/hooks/useNetworks.ts, src/pages/bridge/components/NetworkSelectors.tsx
Adds Optimism to pools & farms.
—
=> Optimism to Pools & Farms

src/hooks/contracts/useLiquidityFarming.ts, src/pages/farms/components/ManageStakingPosition/index.tsx
=> Fix farming claim reward

src/hooks/useNetworks.ts, src/pages/bridge/components/NetworkSelectors.tsx
=> Optimism to bridge

src/pages/bridge/components/TransactionFee.tsx, src/pages/bridge/components/TransferModal/index.tsx, src/pages/pools/components/PoolsOverview/Pools/PoolOverview/index.tsx, src/pages/pools/components/PoolsOverview/Pools/index.tsx, tailwind.config.js
https://biconomy-tech.atlassian.net/browse/HP-198
—
=> HP-198: Add pool cap to mobile layout within pools.

src/config/constants.ts, src/hooks/contracts/useLiquidityFarming.ts, src/hooks/useNetworks.ts, src/pages/bridge/components/NetworkSelectors.tsx, src/pages/farms/components/FarmsOverview/Farms/FarmOverview/index.tsx, src/pages/farms/components/ManageStakingPosition/index.tsx, src/pages/farms/components/StakingPositionOverview.tsx, src/pages/pools/components/AddLiquidity/index.tsx, src/pages/pools/components/LiquidityPositionOverview.tsx, src/pages/pools/components/PoolsOverview/Pools/PoolOverview/index.tsx
=> Enable Arbitrum on Pools & Farms

src/index.tsx, src/pages/bridge/Bridge.tsx, src/pages/bridge/components/UserInfoModal/index.tsx
https://biconomy-tech.atlassian.net/browse/HP-130
**Depends on:**
#181
—
=> HP-130: Lazy loading components which are not required immediately. (to master-v2).

.github/workflows/integration-v2.yml
=> feat:openID

.github/workflows/integration-v2.yml, .github/workflows/production-v2.yml, .github/workflows/staging-v2.yml
=> feat:staging-v2-openID

.github/workflows/integration-v2.yml, .github/workflows/production-v2.yml, .github/workflows/staging-v2.yml
=> feat:production-v2-openID

.github/workflows/integration-v1.yml, .github/workflows/production-v1.yml, .github/workflows/staging-v1.yml
=> feat:staging-v1-openID

.github/workflows/integration.yml, .github/workflows/production.yml, .github/workflows/staging.yml
=> feat:production-v1-openID

package.json, src/pages/bridge/Bridge.tsx, yarn.lock
https://biconomy-tech.atlassian.net/browse/HP-369
=> HP-369: Use Hyphen Widget on the Hyphen website
